# Generated by Django 2.2.13 on 2020-09-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='instance_id',
            field=models.IntegerField(null=True),
        ),
    ]
