# Generated by Django 2.2.13 on 2021-04-16 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0009_auto_20210416_1741'),
        ('programs', '0008_auto_20200803_0905'),
        ('posts', '0002_interaction_instance_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='area_id',
        ),
        migrations.AddField(
            model_name='post',
            name='ar_id',
            field=models.IntegerField(choices=[(1, 'Cognitivo'), (2, 'Motor'), (3, 'Emocional')], default=1, null=True, verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='post',
            name='area',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='areas.Area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='programs',
            field=models.ManyToManyField(to='programs.Program'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
