# Generated by Django 2.2.13 on 2020-08-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200821_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='instance_id',
            field=models.IntegerField(null=True),
        ),
    ]
