# Generated by Django 2.2.13 on 2021-04-16 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_articlefeedback'),
        ('user_sessions', '0014_auto_20210416_1741'),
        ('programs', '0009_auto_20210416_1741'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.RemoveField(
            model_name='articletranslate',
            name='max',
        ),
        migrations.RemoveField(
            model_name='articletranslate',
            name='min',
        ),
        migrations.RemoveField(
            model_name='articletranslate',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='articletranslate',
            name='user',
        ),
        migrations.AddField(
            model_name='article',
            name='programs',
            field=models.ManyToManyField(to='programs.Program'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='value',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='topics',
            field=models.ManyToManyField(to='topics.Topic'),
        ),
        migrations.AlterField(
            model_name='articletranslate',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='languages.Language'),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='topics',
            field=models.ManyToManyField(to='topics.Topic'),
        ),
        migrations.AddField(
            model_name='articlefeedback',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article'),
        ),
    ]
