# Generated by Django 2.2.13 on 2021-04-16 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_users', '0011_auto_20200401_1755'),
        ('bots', '0006_auto_20200328_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinteraction',
            name='Interaction',
        ),
        migrations.RemoveField(
            model_name='userinteraction',
            name='user_id',
        ),
        migrations.AddField(
            model_name='bot',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='interaction',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='bots.Interaction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='messenger_users.User'),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
