# Generated by Django 2.2.13 on 2021-04-16 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_auto_20200329_1028'),
        ('languages', '0014_language_label'),
        ('licences', '0001_initial'),
        ('attributes', '0005_attribute_attribute_view'),
        ('messenger_users', '0011_auto_20200401_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='entities.Entity'),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='languages.Language'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='license',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='licences.License'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attributes.Attribute'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='data_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='UserChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.IntegerField()),
                ('channel_id', models.IntegerField()),
                ('bot_channel_id', models.CharField(max_length=50)),
                ('user_channel_id', models.CharField(max_length=20)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('live_chat', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger_users.User')),
            ],
        ),
        migrations.CreateModel(
            name='LiveChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_chat', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger_users.UserChannel')),
            ],
        ),
    ]
