# Generated by Django 2.2.13 on 2021-04-16 23:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0009_auto_20210416_1741'),
        ('milestones', '0004_auto_20200320_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('step', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='area',
        ),
        migrations.AddField(
            model_name='milestone',
            name='areas',
            field=models.ManyToManyField(to='areas.Area'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='init_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='max',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='min',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
