# Generated by Django 2.2.13 on 2020-08-09 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0002_auto_20200807_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_sessions.Session'),
            preserve_default=False,
        ),
    ]
