# Generated by Django 2.2.13 on 2020-08-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0008_session_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='value',
            field=models.IntegerField(verbose_name='Months'),
        ),
    ]
