# Generated by Django 2.2.13 on 2020-08-21 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200821_1008'),
        ('user_sessions', '0010_remove_session_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='session',
            name='parent_session',
        ),
        migrations.RemoveField(
            model_name='session',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='session',
            name='value',
        ),
        migrations.AddField(
            model_name='session',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish; Castilian'), ('ar', 'Arabic')], default='en', max_length=10, verbose_name='idioma'),
        ),
        migrations.AddField(
            model_name='session',
            name='max',
            field=models.IntegerField(default=72, null=True, verbose_name='Max meses'),
        ),
        migrations.AddField(
            model_name='session',
            name='min',
            field=models.IntegerField(default=0, null=True, verbose_name='Min meses'),
        ),
        migrations.AddField(
            model_name='session',
            name='topics',
            field=models.ManyToManyField(to='articles.Topic'),
        ),
        migrations.CreateModel(
            name='DemographicReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('en', 'English'), ('es', 'Spanish; Castilian'), ('ar', 'Arabic')], default='en', max_length=10, verbose_name='idioma')),
                ('reply', models.TextField()),
                ('value', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demographic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Demographic')),
            ],
        ),
        migrations.CreateModel(
            name='DemographicQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('en', 'English'), ('es', 'Spanish; Castilian'), ('ar', 'Arabic')], default='en', max_length=10, verbose_name='idioma')),
                ('question', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demographic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Demographic')),
            ],
        ),
    ]
