# Generated by Django 2.2.13 on 2020-09-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0012_auto_20200902_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='text',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
