# Generated by Django 2.2.13 on 2021-04-16 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_auto_20200803_0905'),
        ('milestones', '0005_auto_20210416_1741'),
        ('messenger_users', '0011_auto_20200401_1755'),
        ('instances', '0019_auto_20200521_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instanceassociationuser',
            name='user_id',
        ),
        migrations.AddField(
            model_name='instance',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='programs.Program'),
        ),
        migrations.AddField(
            model_name='instance',
            name='sessions',
            field=models.ManyToManyField(to='milestones.Session'),
        ),
        migrations.AddField(
            model_name='instanceassociationuser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='messenger_users.User'),
        ),
        migrations.AddField(
            model_name='response',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='milestones.Session'),
        ),
    ]
