# Generated by Django 2.2.13 on 2021-04-16 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0014_language_label'),
        ('milestones', '0005_auto_20210416_1741'),
        ('attributes', '0005_attribute_attribute_view'),
        ('entities', '0003_auto_20200329_1028'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('areas', '0009_auto_20210416_1741'),
        ('programs', '0008_auto_20200803_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='program',
        ),
        migrations.AddField(
            model_name='level',
            name='image',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='areas',
            field=models.ManyToManyField(to='areas.Area'),
        ),
        migrations.AddField(
            model_name='program',
            name='languages',
            field=models.ManyToManyField(to='languages.Language'),
        ),
        migrations.AddField(
            model_name='program',
            name='levels',
            field=models.ManyToManyField(to='programs.Level'),
        ),
        migrations.AddField(
            model_name='program',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProgramMilestoneValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('min', models.IntegerField(default=0)),
                ('max', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milestones.Milestone')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Program')),
            ],
        ),
        migrations.CreateModel(
            name='LevelLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.Language')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Level')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('weight', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.Entity')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.Program')),
            ],
        ),
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(null=True)),
                ('threshold', models.FloatField(null=True)),
                ('label', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attributes.Attribute')),
                ('attribute_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.AttributeType')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='milestones',
            field=models.ManyToManyField(through='programs.ProgramMilestoneValue', to='milestones.Milestone'),
        ),
    ]
