# Generated by Django 2.2.13 on 2021-04-16 23:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0001_initial'),
        ('programs', '0008_auto_20200803_0905'),
        ('milestones', '0005_auto_20210416_1741'),
        ('messenger_users', '0011_auto_20200401_1755'),
        ('groups', '0012_permission_add_code_to_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignationmessengeruser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='messenger_users.User'),
        ),
        migrations.AddField(
            model_name='group',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='group',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='licences.License'),
        ),
        migrations.AddField(
            model_name='group',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.Group'),
        ),
        migrations.AddField(
            model_name='group',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Región/Departamento/Estado'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='RiskGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(to='groups.Group')),
                ('programs', models.ManyToManyField(to='programs.Program')),
            ],
        ),
        migrations.CreateModel(
            name='MilestoneRisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('percent_value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milestones.Milestone')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.Program')),
                ('risk_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.RiskGroup')),
            ],
        ),
    ]
