from django.urls import path
from programs import views

app_name = 'programs'

urlpatterns = [
    path('', views.ProgramListView.as_view(), name='program_list'),
    path('my_programs/', views.UserProgramListView.as_view(), name='user_program_list'),
    path('new_program/', views.CreateGroupProgramView.as_view(), name='program_create'),
    path('new_group_program/', views.CreateGroupProgramView.as_view(), name='group_program_create'),
    path('<int:program_id>/', views.ProgramDetailView.as_view(), name='program_detail'),
    path('<int:program_id>/metrics/', views.ProgramMetricsView.as_view(), name='program_metrics'),
    path('<int:program_id>/content/', views.ProgramDetailContentView.as_view(), name='program_content_detail'),
    path('<int:program_id>/set_areas/', views.ProgramSetAreasView.as_view(), name='program_set_areas'),
    path('<int:program_id>/edit/', views.ProgramUpdateView.as_view(), name='program_edit'),
    path('<int:program_id>/delete/', views.ProgramDeleteView.as_view(), name='program_delete'),
    path('<int:program_id>/levels/', views.LevelListView.as_view(), name='level_list'),
    path('<int:program_id>/new_level/', views.LevelCreateView.as_view(), name='level_create'),
    path('<int:program_id>/level/<int:level_id>/', views.LevelDetailView.as_view(), name='level_detail'),
    path('<int:program_id>/level/<int:level_id>/content/', views.LevelContentView.as_view(), name='level_content'),
    path('<int:program_id>/level/<int:level_id>/topic/<int:topic_id>/', views.ProgramLevelTopicDetailView.as_view(),
         name='level_topic_detail'),
    path('<int:program_id>/session/<int:session_id>/', views.ProgramSessionDetailView.as_view(),
         name='level_session_detail'),
    path('<int:program_id>/level/<int:level_id>/edit/', views.LevelUpdateView.as_view(), name='level_edit'),
    path('<int:program_id>/level/<int:level_id>/delete/', views.LevelDeleteView.as_view(), name='level_delete'),
    path('<int:program_id>/level/<int:level_id>/add_milestone/', views.LevelMilestoneCreateView.as_view(),
         name='add_level_milestone'),
    path('<int:program_id>/exclude_field/<int:field_id>/', views.ExcludeFieldToProgramView.as_view(),
         name='exclude_field'),
    path('<int:program_id>/comment_field/<int:field_id>/', views.FieldProgramCommentCreateView.as_view(),
         name='comment_field'),
    path('<int:program_id>/program_milestones/', views.ProgramMilestoneListView.as_view(),
         name='program_milestones_list'),
    path('<int:program_id>/create_milestone_association/', views.ProgramMilestoneCreateView.as_view(),
         name='create_program_milestone'),
    path('<int:program_id>/milestone_associations/<int:association_id>/edit/',
         views.ProgramMilestoneEditView.as_view(), name='edit_program_milestone'),
    path('<int:program_id>/milestone_associations/<int:association_id>/delete/',
         views.ProgramMilestoneDeleteView.as_view(), name='delete_program_milestone'),
]
